version: '3.1'
services:
  localstack:
    image: localstack/localstack
    env_file:
      - .docker/local.env
    environment:
      LOCALSTACK_HOST: localstack
      SERVICES: sqs
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:4566/_localstack/health
      interval: 5s
      timeout: 10s
      start_period: 10s
    ports:
      - '4566:4566'
    volumes:
      - ./.docker/localstack:/etc/localstack/init/ready.d
